spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frauddb
    username: fraud
    password: fraudpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
